Traceback (most recent call last):
  File "/Users/adamsochorec/Library/Caches/pypoetry/virtualenvs/applied-machine-learning-AxrkMKCt-py3.13/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/adamsochorec/Library/Caches/pypoetry/virtualenvs/applied-machine-learning-AxrkMKCt-py3.13/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/adamsochorec/Library/Caches/pypoetry/virtualenvs/applied-machine-learning-AxrkMKCt-py3.13/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/adamsochorec/Library/Caches/pypoetry/virtualenvs/applied-machine-learning-AxrkMKCt-py3.13/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/adamsochorec/Library/Caches/pypoetry/virtualenvs/applied-machine-learning-AxrkMKCt-py3.13/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/adamsochorec/Library/Caches/pypoetry/virtualenvs/applied-machine-learning-AxrkMKCt-py3.13/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import seaborn as sns   
sns.set(style='ticks')  
iris = sns.load_dataset('iris')   
print(iris.shape)
print(iris.describe())
iris
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mnumpy[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mnp[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mseaborn[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01msns[39;00m   
[1;32m      3[0m sns[38;5;241m.[39mset(style[38;5;241m=[39m[38;5;124m'[39m[38;5;124mticks[39m[38;5;124m'[39m)  
[1;32m      4[0m iris [38;5;241m=[39m sns[38;5;241m.[39mload_dataset([38;5;124m'[39m[38;5;124miris[39m[38;5;124m'[39m)   

[0;31mModuleNotFoundError[0m: No module named 'seaborn'

